# set_property PACKAGE_PIN W5 [get_ports CLK100MHZ]
#	set_property IOSTANDARD LVCMOS33 [get_ports CLK100MHZ]
#	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK100MHZ]

set_property PACKAGE_PIN U16 [get_ports {out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN E19 [get_ports {out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property PACKAGE_PIN U19 [get_ports {out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property PACKAGE_PIN V19 [get_ports {out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property PACKAGE_PIN W18 [get_ports {out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property PACKAGE_PIN U15 [get_ports {out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property PACKAGE_PIN U14 [get_ports {out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property PACKAGE_PIN V14 [get_ports {out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property PACKAGE_PIN V13 [get_ports {out[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[8]}]
set_property PACKAGE_PIN V3 [get_ports {out[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {out[9]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets flag_IBUF]

set_property PACKAGE_PIN V17 [get_ports {flag[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {flag[0]}]
set_property PACKAGE_PIN V16 [get_ports {flag[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {flag[1]}]
set_property PACKAGE_PIN W16 [get_ports {flag[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {flag[2]}]

set_property PACKAGE_PIN W7 [get_ports {led_out[6]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property PACKAGE_PIN W6 [get_ports {led_out[5]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property PACKAGE_PIN U8 [get_ports {led_out[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property PACKAGE_PIN V8 [get_ports {led_out[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property PACKAGE_PIN U5 [get_ports {led_out[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property PACKAGE_PIN V5 [get_ports {led_out[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property PACKAGE_PIN U7 [get_ports {led_out[0]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]
set_property PACKAGE_PIN U2 [get_ports {activate_anode[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {activate_anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {activate_anode[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {activate_anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {activate_anode[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {activate_anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {activate_anode[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {activate_anode[3]}]
